<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini Framework MVC</title>
</head>

<body>
<style>
    *
    {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
        h1{
            background-color: rgba(14, 45, 78, 0.7);
            height: 70px;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        img {
            display: flex;
            flex-direction: column;
            max-width: 600px;
            margin: 0 auto;
        }
    </style>
    <h1>Index</h1>
    <p>
        <img src="https://file.kelleybluebookimages.com/kbb/base/evox/CP/15115/2023-Honda-Civic-front_15115_032_2400x1800_WX_nologo.png" alt="">
    </p>
    <p>
        <img src="https://resize.indiatvnews.com/en/resize/newbucket/730_-/2021/07/hclmercedesbenz-1626858386.jpg" alt="">
    </p>
    <p>
        <img src="https://media.cnn.com/api/v1/images/stellar/prod/220822155902-01-new-delorean-2022.jpg?c=16x9&q=h_720,w_1280,c_fill/f_webp" alt="">
    </p>
</body>

</html>