<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini Framework MVC</title>
</head>
<body>
    <h1>Produtos novos view</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam sunt ducimus voluptatibus laudantium ea, nisi animi, saepe consequatur obcaecati eveniet voluptatum. Vel dolorem, velit fuga corrupti excepturi repellat sequi? Animi!</p>
    <p>Sequi accusamus ipsam perferendis quasi. Doloribus quaerat iure ullam voluptas tempora quibusdam autem beatae explicabo iste, eum inventore, error exercitationem libero quisquam neque. Cumque fugiat aperiam neque vitae itaque quidem!</p>
    <p>Architecto molestiae nam, aperiam cum, similique, consectetur eos pariatur eaque beatae quaerat molestias atque modi delectus soluta. Fugit sunt, harum voluptate laboriosam, corporis enim eum, iure sapiente officiis quisquam quos.</p>
    <p>Et, libero? Libero voluptate inventore quae tenetur dolores reprehenderit vel omnis illo labore placeat odio, eaque enim quo minus recusandae aperiam eum impedit. Accusantium voluptate, praesentium excepturi harum hic unde.</p>
    <p>Sed vero nesciunt aperiam dicta impedit delectus perferendis esse corrupti dolor cum, ab magni ullam voluptatibus quaerat minus facilis fuga, numquam distinctio deleniti voluptates voluptate perspiciatis. Repellat ab quam sit.</p>
    <p>Aspernatur quaerat consectetur voluptate, quibusdam debitis cupiditate velit consequatur! Inventore optio illum facilis doloremque eos hic fuga ipsam nesciunt, distinctio praesentium! Doloremque harum minus quos! Blanditiis reprehenderit odit a eligendi?</p>
    <p>Labore, similique voluptatibus rem dignissimos laborum, facere error porro veritatis sunt neque eveniet deserunt quam, nobis omnis reprehenderit in quaerat fugiat illum. Voluptate voluptatibus, eum magnam dolore sapiente quis labore.</p>
    <p>Culpa quo eius perspiciatis quae. Minus laudantium ratione neque repellat rem error reprehenderit incidunt quisquam veritatis dicta? Aliquid dolores et fugit deleniti accusantium, fuga praesentium, laboriosam assumenda minus hic numquam!</p>
    <p>Ut excepturi in beatae maxime doloribus modi nam quo facere, assumenda ipsum quas. Minima voluptas harum aspernatur exercitationem quos eos? Voluptate dolore fugiat quasi ex obcaecati distinctio deserunt aut ullam?</p>
    <p>Incidunt perferendis rem expedita laudantium. Eum blanditiis quaerat tenetur unde reiciendis obcaecati officia ex ipsam porro saepe non in qui nisi fuga quos, amet, assumenda quasi nostrum, odit dolorem dicta.</p>
</body>
</html>