<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini Framework MVC</title>
</head>
<body>
    <h1>Produtos da Index</h1>
    <ul>
        <li>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae adipisci facilis architecto, nisi voluptates ex.</li>
        <li>Animi harum aperiam rem ad aspernatur dicta fugit impedit cumque provident! Sunt laborum aspernatur aliquam.</li>
        <li>Facere sequi excepturi provident ipsum, voluptatem deleniti unde voluptas rem harum sapiente veniam quam dolor.</li>
        <li>Ullam error debitis, nemo cumque ducimus cum praesentium magnam, enim obcaecati quae consequuntur natus neque.</li>
        <li>Similique dolores, necessitatibus debitis, fugit repellendus, architecto nihil doloremque nesciunt enim eum eaque maxime quibusdam?</li>
        <li>Expedita dolores ratione sunt sit consectetur optio est eaque dignissimos, nostrum unde voluptatem amet obcaecati!</li>
        <li>At autem incidunt atque expedita nobis nam? Reiciendis sequi laborum asperiores unde enim. Magnam, inventore?</li>
        <li>Porro sapiente, enim labore ipsam in commodi tempore ex itaque nihil veritatis deleniti totam deserunt!</li>
        <li>Fugit inventore, nemo iste earum culpa voluptatum velit et. Modi a neque quo sunt blanditiis.</li>
        <li>Nobis perspiciatis, laborum voluptas exercitationem temporibus numquam at, delectus veniam fugiat corporis aliquam expedita beatae!</li>
        <li>Pariatur unde doloremque non voluptatem sapiente, modi aut, quas voluptatum nisi nobis impedit accusamus sunt.</li>
        <li>Accusantium odio ab et rerum reprehenderit, quisquam sit aliquam asperiores voluptatum ad nobis nostrum impedit.</li>
        <li>Atque iusto commodi autem doloremque nesciunt explicabo ratione architecto aperiam eos reiciendis, quam beatae accusamus!</li>
        <li>Sunt minus, in placeat possimus corporis dolor atque? Doloremque, quod vero. Quis commodi earum placeat?</li>
        <li>Quisquam maxime praesentium corrupti adipisci quo non, placeat animi, rerum, nemo ab commodi facilis! Nisi?</li>
    </ul>
</body>
</html>